module.exports = {
  transformIgnorePatterns: [
    // transform ES6 modules generated by BuckleScript
    // https://regexr.com/46984
    "/node_modules/(?!@glennsl/bs-jest|bs-platform).+\\.js$"
  ],
  reporters: [
    "default",
    ["jest-junit", {
      suiteName: "jest tests",
      "outputDirectory": "__tests__",
      "outputName": "test-results.xml",
    }]
  ],
  moduleFileExtensions: [
    'js',
  ],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1'
  },
  testMatch: [
    '**/__tests__/*.js'
  ],
  moduleFileExtensions: [
    'js',
    'json'
  ],
}