// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/bs-jest/src/jest.bs.js";
import * as Camelsnakekebab$Camelsnakekebab from "../src/camelsnakekebab.bs.js";

Jest.describe("split words", (function (param) {
        return Jest.test("split 1", (function (param) {
                      return Jest.Expect.toEqual([
                                  "foo",
                                  "bar"
                                ], Jest.Expect.expect(Camelsnakekebab$Camelsnakekebab.split_words("foo bar")));
                    }));
      }));

Jest.describe("split words", (function (param) {
        return Jest.test("split 2", (function (param) {
                      return Jest.Expect.toEqual([
                                  "foo",
                                  "bar"
                                ], Jest.Expect.expect(Camelsnakekebab$Camelsnakekebab.split_words("foo\n\tbar")));
                    }));
      }));

Jest.describe("split words", (function (param) {
        return Jest.test("split 3", (function (param) {
                      return Jest.Expect.toEqual([
                                  "foo",
                                  "bar"
                                ], Jest.Expect.expect(Camelsnakekebab$Camelsnakekebab.split_words("foo-bar")));
                    }));
      }));

Jest.describe("split words", (function (param) {
        return Jest.test("split 4", (function (param) {
                      return Jest.Expect.toEqual([
                                  "foo",
                                  "Bar"
                                ], Jest.Expect.expect(Camelsnakekebab$Camelsnakekebab.split_words("fooBar")));
                    }));
      }));

Jest.describe("split words", (function (param) {
        return Jest.test("split 5", (function (param) {
                      return Jest.Expect.toEqual([
                                  "Foo",
                                  "Bar"
                                ], Jest.Expect.expect(Camelsnakekebab$Camelsnakekebab.split_words("FooBar")));
                    }));
      }));

Jest.describe("split words", (function (param) {
        return Jest.test("upper_snake_case", (function (param) {
                      return Jest.Expect.toEqual("A_Snake_Slithers_Slyly", Jest.Expect.expect(Camelsnakekebab$Camelsnakekebab.upper_snake_case("ASnakeSlithersSlyly")));
                    }));
      }));

export {
  
}
/*  Not a pure module */
