// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Camelsnakekebab = require("../src/camelsnakekebab.bs.js");

describe("split words", (function () {
        return Jest.test("split 1", (function (param) {
                      return Jest.Expect[/* toEqual */12](/* array */[
                                  "foo",
                                  "bar"
                                ], Jest.Expect[/* expect */0](Camelsnakekebab.split_words("foo bar")));
                    }));
      }));

describe("split words", (function () {
        return Jest.test("split 2", (function (param) {
                      return Jest.Expect[/* toEqual */12](/* array */[
                                  "foo",
                                  "bar"
                                ], Jest.Expect[/* expect */0](Camelsnakekebab.split_words("foo\n\tbar")));
                    }));
      }));

describe("split words", (function () {
        return Jest.test("split 3", (function (param) {
                      return Jest.Expect[/* toEqual */12](/* array */[
                                  "foo",
                                  "bar"
                                ], Jest.Expect[/* expect */0](Camelsnakekebab.split_words("foo-bar")));
                    }));
      }));

describe("split words", (function () {
        return Jest.test("split 4", (function (param) {
                      return Jest.Expect[/* toEqual */12](/* array */[
                                  "foo",
                                  "Bar"
                                ], Jest.Expect[/* expect */0](Camelsnakekebab.split_words("fooBar")));
                    }));
      }));

describe("split words", (function () {
        return Jest.test("split 5", (function (param) {
                      return Jest.Expect[/* toEqual */12](/* array */[
                                  "Foo",
                                  "Bar"
                                ], Jest.Expect[/* expect */0](Camelsnakekebab.split_words("FooBar")));
                    }));
      }));

describe("split words", (function () {
        return Jest.test("upper_snake_case", (function (param) {
                      return Jest.Expect[/* toEqual */12]("A_Snake_Slithers_Slyly", Jest.Expect[/* expect */0](Camelsnakekebab.upper_snake_case("ASnakeSlithersSlyly")));
                    }));
      }));

/*  Not a pure module */
